/* Generated by scripts/generate-last-modified.mjs. Do not edit by hand:
   the next build overwrites it. Each value is the committer date of the
   last commit that touched the files the route is rendered from, so a
   page's `lastmod` in the sitemap moves when that page changes and stays
   put when it does not.

   Checked in deliberately. See the header of the script for why. */

/** The earliest date any route may claim, used when a route has no git
    history and by the sitemap when a key is missing from the map below. */
export const LAST_MODIFIED_FALLBACK = "2026-07-31T00:00:00.000Z";

export const lastModified: Record<string, string> = {
  "/": "2026-08-18T08:33:33.000Z",
  "/about": "2026-08-18T08:33:33.000Z",
  "/blog": "2026-08-17T22:38:04.000Z",
  "/components": "2026-08-01T00:33:12.000Z",
  "/talks": "2026-08-17T22:38:04.000Z",
  "/components/brand-values-dial": "2026-08-01T00:33:34.000Z",
  "/components/color-pills": "2026-08-01T00:33:34.000Z",
  "/components/decode-flow": "2026-08-01T00:33:34.000Z",
  "/components/expandable-features": "2026-08-01T00:33:34.000Z",
  "/components/isometric-brands": "2026-08-01T00:33:34.000Z",
  "/components/whatsapp-screen": "2026-08-01T00:33:34.000Z",
  "/work": "2026-08-18T08:33:33.000Z",
};
