name: OS Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: clean install
        run: npm ci
      - run: npm run test
      - run: npm run build

      - name: Upload artifact (detailed report)
        uses: actions/upload-artifact@v3
        with:
          name: next-report
          path: next-report/
